---
name: Python build

#
# Global variables from project settings:
#   PYTHON_VERSION: The minimum Python version to support.
#   PYTHON_VERSIONS: The Python versions to test. Usually a list of newer versions we support.
#

# yamllint disable-line rule:truthy
on: pull_request
# yamllint enable rule:comments

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/python_python_callable.yml@412356539ea6525b349518ae02d08909e547161d # 1.21.1
    secrets: inherit
    with:
      # type: string
      # required: true
      # description: The minimum Python version to support
      python-version: ${{ vars.PYTHON_VERSION }}
      # type: string
      # required: true
      # description: The Python versions to test. Usually a list of newer versions we support.
      python-versions: ${{ vars.PYTHON_VERSIONS }}
      # type: string
      # required: false
      # description: "Name of the image. Usually it is sensible to set this to the repository name."
      # default: ""
      docker-image-name: ${{ github.event.repository.name }}
