---

#
# Global variables from project settings:
#   PYTHON_VERSION: The minimum Python version to support.
#   PYTHON_VERSIONS: The Python versions to test. Usually a list of newer versions we support.
#

name: Python build

# yamllint disable-line rule:truthy
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        run: |
          python -m pip install -e "."

      - uses: astral-sh/ruff-action@e6390afda04da2e9ef69fe1e2ae0264164550c21 # v3.0.1
        name: Lint on ${{ vars.PYTHON_VERSION }}
        with:
          args: "check"
          # renovate: datasource=github-releases depName=astral-sh/ruff
          version: "0.8.6"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        run: |
          python -m pip install -e ".[test]"

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./tests/docker-compose.yml"

      - name: Test on ${{ matrix.python-version }}
        run: |
          export AWS_DEFAULT_REGION="eu-central-1"
          pytest -v --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
