---
name: Execute ChatOps help command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@91972445da9e92825c8c983c38c3b5ef9635dd68 # 1.19.1
    secrets: inherit
